// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prefect
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ## Import
    /// 
    /// Prefect Accounts can be imported using the account's UUID
    /// 
    /// ```sh
    /// $ pulumi import prefect:index/account:Account example 00000000-0000-0000-0000-000000000000
    /// ```
    /// </summary>
    [PrefectResourceType("prefect:index/account:Account")]
    public partial class Account : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether or not this account allows public workspaces
        /// </summary>
        [Output("allowPublicWorkspaces")]
        public Output<bool?> AllowPublicWorkspaces { get; private set; } = null!;

        /// <summary>
        /// Billing email to apply to the account's Stripe customer
        /// </summary>
        [Output("billingEmail")]
        public Output<string?> BillingEmail { get; private set; } = null!;

        /// <summary>
        /// Timestamp of when the resource was created (RFC3339)
        /// </summary>
        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// Unique handle of the account
        /// </summary>
        [Output("handle")]
        public Output<string> Handle { get; private set; } = null!;

        /// <summary>
        /// An optional for an external url associated with the account, e.g. https://prefect.io/
        /// </summary>
        [Output("link")]
        public Output<string?> Link { get; private set; } = null!;

        /// <summary>
        /// An optional physical location for the account, e.g. Washington, D.C.
        /// </summary>
        [Output("location")]
        public Output<string?> Location { get; private set; } = null!;

        /// <summary>
        /// Name of the account
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Timestamp of when the resource was updated (RFC3339)
        /// </summary>
        [Output("updated")]
        public Output<string> Updated { get; private set; } = null!;


        /// <summary>
        /// Create a Account resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Account(string name, AccountArgs args, CustomResourceOptions? options = null)
            : base("prefect:index/account:Account", name, args ?? new AccountArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Account(string name, Input<string> id, AccountState? state = null, CustomResourceOptions? options = null)
            : base("prefect:index/account:Account", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/ru5j4r0/pulumi-prefect/releases/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Account resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Account Get(string name, Input<string> id, AccountState? state = null, CustomResourceOptions? options = null)
        {
            return new Account(name, id, state, options);
        }
    }

    public sealed class AccountArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether or not this account allows public workspaces
        /// </summary>
        [Input("allowPublicWorkspaces")]
        public Input<bool>? AllowPublicWorkspaces { get; set; }

        /// <summary>
        /// Billing email to apply to the account's Stripe customer
        /// </summary>
        [Input("billingEmail")]
        public Input<string>? BillingEmail { get; set; }

        /// <summary>
        /// Unique handle of the account
        /// </summary>
        [Input("handle", required: true)]
        public Input<string> Handle { get; set; } = null!;

        /// <summary>
        /// An optional for an external url associated with the account, e.g. https://prefect.io/
        /// </summary>
        [Input("link")]
        public Input<string>? Link { get; set; }

        /// <summary>
        /// An optional physical location for the account, e.g. Washington, D.C.
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// Name of the account
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public AccountArgs()
        {
        }
        public static new AccountArgs Empty => new AccountArgs();
    }

    public sealed class AccountState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether or not this account allows public workspaces
        /// </summary>
        [Input("allowPublicWorkspaces")]
        public Input<bool>? AllowPublicWorkspaces { get; set; }

        /// <summary>
        /// Billing email to apply to the account's Stripe customer
        /// </summary>
        [Input("billingEmail")]
        public Input<string>? BillingEmail { get; set; }

        /// <summary>
        /// Timestamp of when the resource was created (RFC3339)
        /// </summary>
        [Input("created")]
        public Input<string>? Created { get; set; }

        /// <summary>
        /// Unique handle of the account
        /// </summary>
        [Input("handle")]
        public Input<string>? Handle { get; set; }

        /// <summary>
        /// An optional for an external url associated with the account, e.g. https://prefect.io/
        /// </summary>
        [Input("link")]
        public Input<string>? Link { get; set; }

        /// <summary>
        /// An optional physical location for the account, e.g. Washington, D.C.
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// Name of the account
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Timestamp of when the resource was updated (RFC3339)
        /// </summary>
        [Input("updated")]
        public Input<string>? Updated { get; set; }

        public AccountState()
        {
        }
        public static new AccountState Empty => new AccountState();
    }
}
