// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prefect
{
    public static class GetAccountMembers
    {
        /// <summary>
        /// Get information about all members of account.
        /// &lt;br&gt;
        /// Use this data source to obtain user or actor IDs to manage Workspace Access.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prefect = Pulumi.Prefect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allMembers = Prefect.GetAccountMembers.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetAccountMembersResult> InvokeAsync(GetAccountMembersArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAccountMembersResult>("prefect:index/getAccountMembers:getAccountMembers", args ?? new GetAccountMembersArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about all members of account.
        /// &lt;br&gt;
        /// Use this data source to obtain user or actor IDs to manage Workspace Access.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prefect = Pulumi.Prefect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allMembers = Prefect.GetAccountMembers.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetAccountMembersResult> Invoke(GetAccountMembersInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountMembersResult>("prefect:index/getAccountMembers:getAccountMembers", args ?? new GetAccountMembersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAccountMembersArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        [Input("accountId")]
        public string? AccountId { get; set; }

        public GetAccountMembersArgs()
        {
        }
        public static new GetAccountMembersArgs Empty => new GetAccountMembersArgs();
    }

    public sealed class GetAccountMembersInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        public GetAccountMembersInvokeArgs()
        {
        }
        public static new GetAccountMembersInvokeArgs Empty => new GetAccountMembersInvokeArgs();
    }


    [OutputType]
    public sealed class GetAccountMembersResult
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        public readonly string? AccountId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of Account members of an account
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAccountMembersMemberResult> Members;

        [OutputConstructor]
        private GetAccountMembersResult(
            string? accountId,

            string id,

            ImmutableArray<Outputs.GetAccountMembersMemberResult> members)
        {
            AccountId = accountId;
            Id = id;
            Members = members;
        }
    }
}
