// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prefect
{
    public static class GetVariable
    {
        /// <summary>
        /// Get information about an existing Variable by name or ID.
        /// &lt;br&gt;
        /// Use this data source to obtain Variable-specific attributes, such as the value.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prefect = Pulumi.Prefect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var existingById = Prefect.GetVariable.Invoke(new()
        ///     {
        ///         Id = "00000000-0000-0000-0000-000000000000",
        ///     });
        /// 
        ///     var existingByName = Prefect.GetVariable.Invoke(new()
        ///     {
        ///         Name = "my_variable_name",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetVariableResult> InvokeAsync(GetVariableArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVariableResult>("prefect:index/getVariable:getVariable", args ?? new GetVariableArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about an existing Variable by name or ID.
        /// &lt;br&gt;
        /// Use this data source to obtain Variable-specific attributes, such as the value.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prefect = Pulumi.Prefect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var existingById = Prefect.GetVariable.Invoke(new()
        ///     {
        ///         Id = "00000000-0000-0000-0000-000000000000",
        ///     });
        /// 
        ///     var existingByName = Prefect.GetVariable.Invoke(new()
        ///     {
        ///         Name = "my_variable_name",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetVariableResult> Invoke(GetVariableInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVariableResult>("prefect:index/getVariable:getVariable", args ?? new GetVariableInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVariableArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        [Input("accountId")]
        public string? AccountId { get; set; }

        /// <summary>
        /// Variable ID (UUID)
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Name of the variable
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Workspace ID (UUID), defaults to the workspace set in the provider
        /// </summary>
        [Input("workspaceId")]
        public string? WorkspaceId { get; set; }

        public GetVariableArgs()
        {
        }
        public static new GetVariableArgs Empty => new GetVariableArgs();
    }

    public sealed class GetVariableInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Variable ID (UUID)
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Name of the variable
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Workspace ID (UUID), defaults to the workspace set in the provider
        /// </summary>
        [Input("workspaceId")]
        public Input<string>? WorkspaceId { get; set; }

        public GetVariableInvokeArgs()
        {
        }
        public static new GetVariableInvokeArgs Empty => new GetVariableInvokeArgs();
    }


    [OutputType]
    public sealed class GetVariableResult
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        public readonly string? AccountId;
        /// <summary>
        /// Timestamp of when the resource was created (RFC3339)
        /// </summary>
        public readonly string Created;
        /// <summary>
        /// Variable ID (UUID)
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the variable
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Tags associated with the variable
        /// </summary>
        public readonly ImmutableArray<string> Tags;
        /// <summary>
        /// Timestamp of when the resource was updated (RFC3339)
        /// </summary>
        public readonly string Updated;
        /// <summary>
        /// Value of the variable
        /// </summary>
        public readonly string Value;
        /// <summary>
        /// Workspace ID (UUID), defaults to the workspace set in the provider
        /// </summary>
        public readonly string? WorkspaceId;

        [OutputConstructor]
        private GetVariableResult(
            string? accountId,

            string created,

            string id,

            string name,

            ImmutableArray<string> tags,

            string updated,

            string value,

            string? workspaceId)
        {
            AccountId = accountId;
            Created = created;
            Id = id;
            Name = name;
            Tags = tags;
            Updated = updated;
            Value = value;
            WorkspaceId = workspaceId;
        }
    }
}
