// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prefect
{
    public static class GetWorkerMetadata
    {
        /// <summary>
        /// Get metadata information about the common Worker types, such as Kubernetes, ECS, etc.
        /// &lt;br&gt;
        /// Use this data source to get the default base job configurations for those common Worker types.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prefect = Pulumi.Prefect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var workerMetadata = Prefect.GetWorkerMetadata.Invoke();
        /// 
        ///     var kubernetes = new Prefect.WorkPool("kubernetes", new()
        ///     {
        ///         Type = "kubernetes",
        ///         WorkspaceId = data.Prefect_workspace.Prd.Id,
        ///         Paused = false,
        ///         BaseJobTemplate = workerMetadata.Apply(getWorkerMetadataResult =&gt; getWorkerMetadataResult.BaseJobConfigs?.Kubernetes),
        ///     });
        /// 
        ///     var ecs = new Prefect.WorkPool("ecs", new()
        ///     {
        ///         Type = "ecs",
        ///         WorkspaceId = data.Prefect_workspace.Prd.Id,
        ///         Paused = false,
        ///         BaseJobTemplate = workerMetadata.Apply(getWorkerMetadataResult =&gt; getWorkerMetadataResult.BaseJobConfigs?.Ecs),
        ///     });
        /// 
        ///     var process = new Prefect.WorkPool("process", new()
        ///     {
        ///         Type = "cloud-run:push",
        ///         WorkspaceId = data.Prefect_workspace.Prd.Id,
        ///         Paused = false,
        ///         BaseJobTemplate = workerMetadata.Apply(getWorkerMetadataResult =&gt; getWorkerMetadataResult.BaseJobConfigs?.CloudRunPush),
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetWorkerMetadataResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetWorkerMetadataResult>("prefect:index/getWorkerMetadata:getWorkerMetadata", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Get metadata information about the common Worker types, such as Kubernetes, ECS, etc.
        /// &lt;br&gt;
        /// Use this data source to get the default base job configurations for those common Worker types.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prefect = Pulumi.Prefect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var workerMetadata = Prefect.GetWorkerMetadata.Invoke();
        /// 
        ///     var kubernetes = new Prefect.WorkPool("kubernetes", new()
        ///     {
        ///         Type = "kubernetes",
        ///         WorkspaceId = data.Prefect_workspace.Prd.Id,
        ///         Paused = false,
        ///         BaseJobTemplate = workerMetadata.Apply(getWorkerMetadataResult =&gt; getWorkerMetadataResult.BaseJobConfigs?.Kubernetes),
        ///     });
        /// 
        ///     var ecs = new Prefect.WorkPool("ecs", new()
        ///     {
        ///         Type = "ecs",
        ///         WorkspaceId = data.Prefect_workspace.Prd.Id,
        ///         Paused = false,
        ///         BaseJobTemplate = workerMetadata.Apply(getWorkerMetadataResult =&gt; getWorkerMetadataResult.BaseJobConfigs?.Ecs),
        ///     });
        /// 
        ///     var process = new Prefect.WorkPool("process", new()
        ///     {
        ///         Type = "cloud-run:push",
        ///         WorkspaceId = data.Prefect_workspace.Prd.Id,
        ///         Paused = false,
        ///         BaseJobTemplate = workerMetadata.Apply(getWorkerMetadataResult =&gt; getWorkerMetadataResult.BaseJobConfigs?.CloudRunPush),
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetWorkerMetadataResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetWorkerMetadataResult>("prefect:index/getWorkerMetadata:getWorkerMetadata", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetWorkerMetadataResult
    {
        /// <summary>
        /// A map of default base job configurations (JSON) for each of the primary worker types
        /// </summary>
        public readonly Outputs.GetWorkerMetadataBaseJobConfigsResult BaseJobConfigs;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetWorkerMetadataResult(
            Outputs.GetWorkerMetadataBaseJobConfigsResult baseJobConfigs,

            string id)
        {
            BaseJobConfigs = baseJobConfigs;
            Id = id;
        }
    }
}
