// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prefect
{
    public static class GetWorkspace
    {
        /// <summary>
        /// Get information about an existing Workspace by handle.
        /// &lt;br&gt;
        /// Use this data source to obtain Workspace IDs
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prefect = Pulumi.Prefect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var productionEnvironment = Prefect.GetWorkspace.Invoke(new()
        ///     {
        ///         Id = "00000000-0000-0000-0000-000000000000",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetWorkspaceResult> InvokeAsync(GetWorkspaceArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetWorkspaceResult>("prefect:index/getWorkspace:getWorkspace", args ?? new GetWorkspaceArgs(), options.WithDefaults());

        /// <summary>
        /// Get information about an existing Workspace by handle.
        /// &lt;br&gt;
        /// Use this data source to obtain Workspace IDs
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Prefect = Pulumi.Prefect;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var productionEnvironment = Prefect.GetWorkspace.Invoke(new()
        ///     {
        ///         Id = "00000000-0000-0000-0000-000000000000",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetWorkspaceResult> Invoke(GetWorkspaceInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetWorkspaceResult>("prefect:index/getWorkspace:getWorkspace", args ?? new GetWorkspaceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetWorkspaceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        [Input("accountId")]
        public string? AccountId { get; set; }

        /// <summary>
        /// Unique handle for the workspace
        /// </summary>
        [Input("handle")]
        public string? Handle { get; set; }

        /// <summary>
        /// Workspace ID (UUID)
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        public GetWorkspaceArgs()
        {
        }
        public static new GetWorkspaceArgs Empty => new GetWorkspaceArgs();
    }

    public sealed class GetWorkspaceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        [Input("accountId")]
        public Input<string>? AccountId { get; set; }

        /// <summary>
        /// Unique handle for the workspace
        /// </summary>
        [Input("handle")]
        public Input<string>? Handle { get; set; }

        /// <summary>
        /// Workspace ID (UUID)
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        public GetWorkspaceInvokeArgs()
        {
        }
        public static new GetWorkspaceInvokeArgs Empty => new GetWorkspaceInvokeArgs();
    }


    [OutputType]
    public sealed class GetWorkspaceResult
    {
        /// <summary>
        /// Account ID (UUID), defaults to the account set in the provider
        /// </summary>
        public readonly string? AccountId;
        /// <summary>
        /// Timestamp of when the resource was created (RFC3339)
        /// </summary>
        public readonly string Created;
        /// <summary>
        /// Description for the workspace
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Unique handle for the workspace
        /// </summary>
        public readonly string Handle;
        /// <summary>
        /// Workspace ID (UUID)
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the workspace
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Timestamp of when the resource was updated (RFC3339)
        /// </summary>
        public readonly string Updated;

        [OutputConstructor]
        private GetWorkspaceResult(
            string? accountId,

            string created,

            string description,

            string handle,

            string id,

            string name,

            string updated)
        {
            AccountId = accountId;
            Created = created;
            Description = description;
            Handle = handle;
            Id = id;
            Name = name;
            Updated = updated;
        }
    }
}
