# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .account import *
from .get_account import *
from .get_account_member import *
from .get_account_members import *
from .get_account_role import *
from .get_service_account import *
from .get_team import *
from .get_teams import *
from .get_variable import *
from .get_work_pool import *
from .get_work_pools import *
from .get_worker_metadata import *
from .get_workspace import *
from .get_workspace_role import *
from .provider import *
from .service_account import *
from .variable import *
from .work_pool import *
from .workspace import *
from .workspace_access import *
from .workspace_role import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_prefect.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_prefect.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "prefect",
  "mod": "index/account",
  "fqn": "pulumi_prefect",
  "classes": {
   "prefect:index/account:Account": "Account"
  }
 },
 {
  "pkg": "prefect",
  "mod": "index/serviceAccount",
  "fqn": "pulumi_prefect",
  "classes": {
   "prefect:index/serviceAccount:ServiceAccount": "ServiceAccount"
  }
 },
 {
  "pkg": "prefect",
  "mod": "index/variable",
  "fqn": "pulumi_prefect",
  "classes": {
   "prefect:index/variable:Variable": "Variable"
  }
 },
 {
  "pkg": "prefect",
  "mod": "index/workPool",
  "fqn": "pulumi_prefect",
  "classes": {
   "prefect:index/workPool:WorkPool": "WorkPool"
  }
 },
 {
  "pkg": "prefect",
  "mod": "index/workspace",
  "fqn": "pulumi_prefect",
  "classes": {
   "prefect:index/workspace:Workspace": "Workspace"
  }
 },
 {
  "pkg": "prefect",
  "mod": "index/workspaceAccess",
  "fqn": "pulumi_prefect",
  "classes": {
   "prefect:index/workspaceAccess:WorkspaceAccess": "WorkspaceAccess"
  }
 },
 {
  "pkg": "prefect",
  "mod": "index/workspaceRole",
  "fqn": "pulumi_prefect",
  "classes": {
   "prefect:index/workspaceRole:WorkspaceRole": "WorkspaceRole"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "prefect",
  "token": "pulumi:providers:prefect",
  "fqn": "pulumi_prefect",
  "class": "Provider"
 }
]
"""
)
