// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prefect.Outputs
{

    [OutputType]
    public sealed class GetTeamsTeamResult
    {
        /// <summary>
        /// Date and time of the team creation in RFC 3339 format
        /// </summary>
        public readonly string Created;
        /// <summary>
        /// Description of team
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Team ID (UUID)
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of Team
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Date and time that the team was last updated in RFC 3339 format
        /// </summary>
        public readonly string Updated;

        [OutputConstructor]
        private GetTeamsTeamResult(
            string created,

            string description,

            string id,

            string name,

            string updated)
        {
            Created = created;
            Description = description;
            Id = id;
            Name = name;
            Updated = updated;
        }
    }
}
