// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prefect.Outputs
{

    [OutputType]
    public sealed class GetWorkPoolsWorkPoolResult
    {
        /// <summary>
        /// The base job template for the work pool, as a JSON string
        /// </summary>
        public readonly string BaseJobTemplate;
        /// <summary>
        /// The concurrency limit applied to this work pool
        /// </summary>
        public readonly int ConcurrencyLimit;
        /// <summary>
        /// Date and time of the work pool creation in RFC 3339 format
        /// </summary>
        public readonly string Created;
        /// <summary>
        /// The ID (UUID) of the default queue associated with this work pool
        /// </summary>
        public readonly string DefaultQueueId;
        /// <summary>
        /// Description of the work pool
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Work pool ID (UUID)
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Name of the work pool
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Whether this work pool is paused
        /// </summary>
        public readonly bool Paused;
        /// <summary>
        /// Type of the work pool
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Date and time that the work pool was last updated in RFC 3339 format
        /// </summary>
        public readonly string Updated;

        [OutputConstructor]
        private GetWorkPoolsWorkPoolResult(
            string baseJobTemplate,

            int concurrencyLimit,

            string created,

            string defaultQueueId,

            string description,

            string id,

            string name,

            bool paused,

            string type,

            string updated)
        {
            BaseJobTemplate = baseJobTemplate;
            ConcurrencyLimit = concurrencyLimit;
            Created = created;
            DefaultQueueId = defaultQueueId;
            Description = description;
            Id = id;
            Name = name;
            Paused = paused;
            Type = type;
            Updated = updated;
        }
    }
}
