// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Prefect.Outputs
{

    [OutputType]
    public sealed class GetWorkerMetadataBaseJobConfigsResult
    {
        /// <summary>
        /// Default base job configuration for Azure Container Instances workers
        /// </summary>
        public readonly string AzureContainerInstances;
        /// <summary>
        /// Default base job configuration for Azure Container Instances Push workers
        /// </summary>
        public readonly string AzureContainerInstancesPush;
        /// <summary>
        /// Default base job configuration for Cloud Run workers
        /// </summary>
        public readonly string CloudRun;
        /// <summary>
        /// Default base job configuration for Cloud Run Push workers
        /// </summary>
        public readonly string CloudRunPush;
        /// <summary>
        /// Default base job configuration for Docker workers
        /// </summary>
        public readonly string Docker;
        /// <summary>
        /// Default base job configuration for ECS workers
        /// </summary>
        public readonly string Ecs;
        /// <summary>
        /// Default base job configuration for ECS Push workers
        /// </summary>
        public readonly string EcsPush;
        /// <summary>
        /// Default base job configuration for Kubernetes workers
        /// </summary>
        public readonly string Kubernetes;
        /// <summary>
        /// Default base job configuration for Prefect Agent workers
        /// </summary>
        public readonly string PrefectAgent;
        /// <summary>
        /// Default base job configuration for Process workers
        /// </summary>
        public readonly string Process;
        /// <summary>
        /// Default base job configuration for Vertex AI workers
        /// </summary>
        public readonly string VertexAi;

        [OutputConstructor]
        private GetWorkerMetadataBaseJobConfigsResult(
            string azureContainerInstances,

            string azureContainerInstancesPush,

            string cloudRun,

            string cloudRunPush,

            string docker,

            string ecs,

            string ecsPush,

            string kubernetes,

            string prefectAgent,

            string process,

            string vertexAi)
        {
            AzureContainerInstances = azureContainerInstances;
            AzureContainerInstancesPush = azureContainerInstancesPush;
            CloudRun = cloudRun;
            CloudRunPush = cloudRunPush;
            Docker = docker;
            Ecs = ecs;
            EcsPush = ecsPush;
            Kubernetes = kubernetes;
            PrefectAgent = prefectAgent;
            Process = process;
            VertexAi = vertexAi;
        }
    }
}
