// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/ru5j4r0/pulumi-prefect/sdk/go/prefect/internal"
)

var _ = internal.GetEnvOrDefault

// Default Prefect Cloud Account ID. Can also be set via the `PREFECT_CLOUD_ACCOUNT_ID` environment variable.
func GetAccountId(ctx *pulumi.Context) string {
	return config.Get(ctx, "prefect:accountId")
}

// Prefect Cloud API Key. Can also be set via the `PREFECT_API_KEY` environment variable.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "prefect:apiKey")
}

// Prefect API URL. Can also be set via the `PREFECT_API_URL` environment variable. Defaults to `https://api.prefect.cloud`
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "prefect:endpoint")
}

// Default Prefect Cloud Workspace ID.
func GetWorkspaceId(ctx *pulumi.Context) string {
	return config.Get(ctx, "prefect:workspaceId")
}
