// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package prefect

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ru5j4r0/pulumi-prefect/sdk/go/prefect/internal"
)

// Get information about an existing Workspace Role.
// <br>
// Use this data source read down the pre-defined Roles, to manage User and Service Account access.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ru5j4r0/pulumi-prefect/sdk/go/prefect"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := prefect.GetAccountRole(ctx, &prefect.GetAccountRoleArgs{
//				Name: "Admin",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = prefect.GetAccountRole(ctx, &prefect.GetAccountRoleArgs{
//				Name: "Member",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetAccountRole(ctx *pulumi.Context, args *GetAccountRoleArgs, opts ...pulumi.InvokeOption) (*GetAccountRoleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAccountRoleResult
	err := ctx.Invoke("prefect:index/getAccountRole:getAccountRole", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccountRole.
type GetAccountRoleArgs struct {
	// Account ID (UUID) where the resource resides
	AccountId *string `pulumi:"accountId"`
	// Name of the Account Role
	Name string `pulumi:"name"`
}

// A collection of values returned by getAccountRole.
type GetAccountRoleResult struct {
	// Account ID (UUID) where the resource resides
	AccountId *string `pulumi:"accountId"`
	// Timestamp of when the resource was created (RFC3339)
	Created string `pulumi:"created"`
	// Account Role ID (UUID)
	Id string `pulumi:"id"`
	// Boolean specifying if the Account Role is a system role
	IsSystemRole bool `pulumi:"isSystemRole"`
	// Name of the Account Role
	Name string `pulumi:"name"`
	// List of permissions linked to the Account Role
	Permissions []string `pulumi:"permissions"`
	// Timestamp of when the resource was updated (RFC3339)
	Updated string `pulumi:"updated"`
}

func GetAccountRoleOutput(ctx *pulumi.Context, args GetAccountRoleOutputArgs, opts ...pulumi.InvokeOption) GetAccountRoleResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetAccountRoleResult, error) {
			args := v.(GetAccountRoleArgs)
			r, err := GetAccountRole(ctx, &args, opts...)
			var s GetAccountRoleResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetAccountRoleResultOutput)
}

// A collection of arguments for invoking getAccountRole.
type GetAccountRoleOutputArgs struct {
	// Account ID (UUID) where the resource resides
	AccountId pulumi.StringPtrInput `pulumi:"accountId"`
	// Name of the Account Role
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetAccountRoleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccountRoleArgs)(nil)).Elem()
}

// A collection of values returned by getAccountRole.
type GetAccountRoleResultOutput struct{ *pulumi.OutputState }

func (GetAccountRoleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAccountRoleResult)(nil)).Elem()
}

func (o GetAccountRoleResultOutput) ToGetAccountRoleResultOutput() GetAccountRoleResultOutput {
	return o
}

func (o GetAccountRoleResultOutput) ToGetAccountRoleResultOutputWithContext(ctx context.Context) GetAccountRoleResultOutput {
	return o
}

// Account ID (UUID) where the resource resides
func (o GetAccountRoleResultOutput) AccountId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAccountRoleResult) *string { return v.AccountId }).(pulumi.StringPtrOutput)
}

// Timestamp of when the resource was created (RFC3339)
func (o GetAccountRoleResultOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountRoleResult) string { return v.Created }).(pulumi.StringOutput)
}

// Account Role ID (UUID)
func (o GetAccountRoleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountRoleResult) string { return v.Id }).(pulumi.StringOutput)
}

// Boolean specifying if the Account Role is a system role
func (o GetAccountRoleResultOutput) IsSystemRole() pulumi.BoolOutput {
	return o.ApplyT(func(v GetAccountRoleResult) bool { return v.IsSystemRole }).(pulumi.BoolOutput)
}

// Name of the Account Role
func (o GetAccountRoleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountRoleResult) string { return v.Name }).(pulumi.StringOutput)
}

// List of permissions linked to the Account Role
func (o GetAccountRoleResultOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetAccountRoleResult) []string { return v.Permissions }).(pulumi.StringArrayOutput)
}

// Timestamp of when the resource was updated (RFC3339)
func (o GetAccountRoleResultOutput) Updated() pulumi.StringOutput {
	return o.ApplyT(func(v GetAccountRoleResult) string { return v.Updated }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAccountRoleResultOutput{})
}
