// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package prefect

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ru5j4r0/pulumi-prefect/sdk/go/prefect/internal"
)

// Get information about an existing Service Account, by name or ID.
// <br>
// Use this data source to obtain service account-level attributes, such as ID.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ru5j4r0/pulumi-prefect/sdk/go/prefect"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := prefect.LookupServiceAccount(ctx, &prefect.LookupServiceAccountArgs{
//				Name: pulumi.StringRef("my-bot-name"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupServiceAccount(ctx *pulumi.Context, args *LookupServiceAccountArgs, opts ...pulumi.InvokeOption) (*LookupServiceAccountResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupServiceAccountResult
	err := ctx.Invoke("prefect:index/getServiceAccount:getServiceAccount", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServiceAccount.
type LookupServiceAccountArgs struct {
	// Account ID (UUID), defaults to the account set in the provider
	AccountId *string `pulumi:"accountId"`
	// Service Account ID (UUID)
	Id *string `pulumi:"id"`
	// Name of the service account
	Name *string `pulumi:"name"`
}

// A collection of values returned by getServiceAccount.
type LookupServiceAccountResult struct {
	// Account ID (UUID), defaults to the account set in the provider
	AccountId *string `pulumi:"accountId"`
	// Account Role name of the service account
	AccountRoleName string `pulumi:"accountRoleName"`
	// API Key associated with the service account
	ApiKey string `pulumi:"apiKey"`
	// Date and time that the API Key was created in RFC 3339 format
	ApiKeyCreated string `pulumi:"apiKeyCreated"`
	// Date and time that the API Key expires in RFC 3339 format
	ApiKeyExpiration string `pulumi:"apiKeyExpiration"`
	// API Key ID associated with the service account. NOTE: this is always null for reads. If you need the API Key ID, use the `ServiceAccount` resource instead.
	ApiKeyId string `pulumi:"apiKeyId"`
	// API Key Name associated with the service account
	ApiKeyName string `pulumi:"apiKeyName"`
	// Timestamp of when the resource was created (RFC3339)
	Created string `pulumi:"created"`
	// Service Account ID (UUID)
	Id string `pulumi:"id"`
	// Name of the service account
	Name string `pulumi:"name"`
	// Timestamp of when the resource was updated (RFC3339)
	Updated string `pulumi:"updated"`
}

func LookupServiceAccountOutput(ctx *pulumi.Context, args LookupServiceAccountOutputArgs, opts ...pulumi.InvokeOption) LookupServiceAccountResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupServiceAccountResult, error) {
			args := v.(LookupServiceAccountArgs)
			r, err := LookupServiceAccount(ctx, &args, opts...)
			var s LookupServiceAccountResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupServiceAccountResultOutput)
}

// A collection of arguments for invoking getServiceAccount.
type LookupServiceAccountOutputArgs struct {
	// Account ID (UUID), defaults to the account set in the provider
	AccountId pulumi.StringPtrInput `pulumi:"accountId"`
	// Service Account ID (UUID)
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Name of the service account
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupServiceAccountOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServiceAccountArgs)(nil)).Elem()
}

// A collection of values returned by getServiceAccount.
type LookupServiceAccountResultOutput struct{ *pulumi.OutputState }

func (LookupServiceAccountResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupServiceAccountResult)(nil)).Elem()
}

func (o LookupServiceAccountResultOutput) ToLookupServiceAccountResultOutput() LookupServiceAccountResultOutput {
	return o
}

func (o LookupServiceAccountResultOutput) ToLookupServiceAccountResultOutputWithContext(ctx context.Context) LookupServiceAccountResultOutput {
	return o
}

// Account ID (UUID), defaults to the account set in the provider
func (o LookupServiceAccountResultOutput) AccountId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) *string { return v.AccountId }).(pulumi.StringPtrOutput)
}

// Account Role name of the service account
func (o LookupServiceAccountResultOutput) AccountRoleName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.AccountRoleName }).(pulumi.StringOutput)
}

// API Key associated with the service account
func (o LookupServiceAccountResultOutput) ApiKey() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.ApiKey }).(pulumi.StringOutput)
}

// Date and time that the API Key was created in RFC 3339 format
func (o LookupServiceAccountResultOutput) ApiKeyCreated() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.ApiKeyCreated }).(pulumi.StringOutput)
}

// Date and time that the API Key expires in RFC 3339 format
func (o LookupServiceAccountResultOutput) ApiKeyExpiration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.ApiKeyExpiration }).(pulumi.StringOutput)
}

// API Key ID associated with the service account. NOTE: this is always null for reads. If you need the API Key ID, use the `ServiceAccount` resource instead.
func (o LookupServiceAccountResultOutput) ApiKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.ApiKeyId }).(pulumi.StringOutput)
}

// API Key Name associated with the service account
func (o LookupServiceAccountResultOutput) ApiKeyName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.ApiKeyName }).(pulumi.StringOutput)
}

// Timestamp of when the resource was created (RFC3339)
func (o LookupServiceAccountResultOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.Created }).(pulumi.StringOutput)
}

// Service Account ID (UUID)
func (o LookupServiceAccountResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.Id }).(pulumi.StringOutput)
}

// Name of the service account
func (o LookupServiceAccountResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.Name }).(pulumi.StringOutput)
}

// Timestamp of when the resource was updated (RFC3339)
func (o LookupServiceAccountResultOutput) Updated() pulumi.StringOutput {
	return o.ApplyT(func(v LookupServiceAccountResult) string { return v.Updated }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupServiceAccountResultOutput{})
}
