// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package prefect

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ru5j4r0/pulumi-prefect/sdk/go/prefect/internal"
)

// Get information about an multiple Work Pools.
// <br>
// Use this data source to search for multiple Work Pools. Defaults to fetching all Work Pools in the Workspace.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ru5j4r0/pulumi-prefect/sdk/go/prefect"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := prefect.GetWorkPools(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetWorkPools(ctx *pulumi.Context, args *GetWorkPoolsArgs, opts ...pulumi.InvokeOption) (*GetWorkPoolsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetWorkPoolsResult
	err := ctx.Invoke("prefect:index/getWorkPools:getWorkPools", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getWorkPools.
type GetWorkPoolsArgs struct {
	// Account ID (UUID), defaults to the account set in the provider
	AccountId *string `pulumi:"accountId"`
	// Work pool IDs (UUID) to search for (work pools with any matching UUID are returned)
	FilterAnies []string `pulumi:"filterAnies"`
	// Workspace ID (UUID), defaults to the workspace set in the provider
	WorkspaceId *string `pulumi:"workspaceId"`
}

// A collection of values returned by getWorkPools.
type GetWorkPoolsResult struct {
	// Account ID (UUID), defaults to the account set in the provider
	AccountId *string `pulumi:"accountId"`
	// Work pool IDs (UUID) to search for (work pools with any matching UUID are returned)
	FilterAnies []string `pulumi:"filterAnies"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Work pools returned by the server
	WorkPools []GetWorkPoolsWorkPool `pulumi:"workPools"`
	// Workspace ID (UUID), defaults to the workspace set in the provider
	WorkspaceId *string `pulumi:"workspaceId"`
}

func GetWorkPoolsOutput(ctx *pulumi.Context, args GetWorkPoolsOutputArgs, opts ...pulumi.InvokeOption) GetWorkPoolsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetWorkPoolsResult, error) {
			args := v.(GetWorkPoolsArgs)
			r, err := GetWorkPools(ctx, &args, opts...)
			var s GetWorkPoolsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetWorkPoolsResultOutput)
}

// A collection of arguments for invoking getWorkPools.
type GetWorkPoolsOutputArgs struct {
	// Account ID (UUID), defaults to the account set in the provider
	AccountId pulumi.StringPtrInput `pulumi:"accountId"`
	// Work pool IDs (UUID) to search for (work pools with any matching UUID are returned)
	FilterAnies pulumi.StringArrayInput `pulumi:"filterAnies"`
	// Workspace ID (UUID), defaults to the workspace set in the provider
	WorkspaceId pulumi.StringPtrInput `pulumi:"workspaceId"`
}

func (GetWorkPoolsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWorkPoolsArgs)(nil)).Elem()
}

// A collection of values returned by getWorkPools.
type GetWorkPoolsResultOutput struct{ *pulumi.OutputState }

func (GetWorkPoolsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetWorkPoolsResult)(nil)).Elem()
}

func (o GetWorkPoolsResultOutput) ToGetWorkPoolsResultOutput() GetWorkPoolsResultOutput {
	return o
}

func (o GetWorkPoolsResultOutput) ToGetWorkPoolsResultOutputWithContext(ctx context.Context) GetWorkPoolsResultOutput {
	return o
}

// Account ID (UUID), defaults to the account set in the provider
func (o GetWorkPoolsResultOutput) AccountId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetWorkPoolsResult) *string { return v.AccountId }).(pulumi.StringPtrOutput)
}

// Work pool IDs (UUID) to search for (work pools with any matching UUID are returned)
func (o GetWorkPoolsResultOutput) FilterAnies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetWorkPoolsResult) []string { return v.FilterAnies }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetWorkPoolsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetWorkPoolsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Work pools returned by the server
func (o GetWorkPoolsResultOutput) WorkPools() GetWorkPoolsWorkPoolArrayOutput {
	return o.ApplyT(func(v GetWorkPoolsResult) []GetWorkPoolsWorkPool { return v.WorkPools }).(GetWorkPoolsWorkPoolArrayOutput)
}

// Workspace ID (UUID), defaults to the workspace set in the provider
func (o GetWorkPoolsResultOutput) WorkspaceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetWorkPoolsResult) *string { return v.WorkspaceId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetWorkPoolsResultOutput{})
}
