name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  publish_binary:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: provider/go.mod
        cache-dependency-path: |
          provider/go.sum
          provider/shim/go.sum
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.11.0
      with:
        repo: pulumi/pulumictl
    - name: Set PreRelease Version
      run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        args: release --clean
        version: latest
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    strategy:
      fail-fast: true
  publish_sdk:
    name: Publish SDKs
    runs-on: ubuntu-latest
    needs: publish_binary
    steps:
    - id: version
      uses: pulumi/provider-version-action@main
    - name: Publish SDKs
      uses: pulumi/pulumi-package-publisher@v0.0.15
      with:
        version: '${{ steps.version.outputs.version }}'
        sdk: python
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        GOVERSION: '1.22'
        PYTHONVERSION: '3.12'
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: '${{ secrets.PYPI_TOKEN }}'
    strategy:
      fail-fast: true
