// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Get information about all members of account.
 * <br>
 * Use this data source to obtain user or actor IDs to manage Workspace Access.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prefect from "@pulumi/prefect";
 *
 * const allMembers = prefect.getAccountMembers({});
 * ```
 */
export function getAccountMembers(args?: GetAccountMembersArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountMembersResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prefect:index/getAccountMembers:getAccountMembers", {
        "accountId": args.accountId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccountMembers.
 */
export interface GetAccountMembersArgs {
    /**
     * Account ID (UUID), defaults to the account set in the provider
     */
    accountId?: string;
}

/**
 * A collection of values returned by getAccountMembers.
 */
export interface GetAccountMembersResult {
    /**
     * Account ID (UUID), defaults to the account set in the provider
     */
    readonly accountId?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of Account members of an account
     */
    readonly members: outputs.GetAccountMembersMember[];
}
/**
 * Get information about all members of account.
 * <br>
 * Use this data source to obtain user or actor IDs to manage Workspace Access.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prefect from "@pulumi/prefect";
 *
 * const allMembers = prefect.getAccountMembers({});
 * ```
 */
export function getAccountMembersOutput(args?: GetAccountMembersOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAccountMembersResult> {
    return pulumi.output(args).apply((a: any) => getAccountMembers(a, opts))
}

/**
 * A collection of arguments for invoking getAccountMembers.
 */
export interface GetAccountMembersOutputArgs {
    /**
     * Account ID (UUID), defaults to the account set in the provider
     */
    accountId?: pulumi.Input<string>;
}
