// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get information about an existing Account Member (user)	by their email.
 * <br>
 * Use this data source to obtain user or actor IDs to manage Workspace Access.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prefect from "@pulumi/prefect";
 *
 * const marvin = prefect.getAccountMember({
 *     email: "marvin@prefect.io",
 * });
 * ```
 */
export function getAccountMember(args: GetAccountMemberArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountMemberResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("prefect:index/getAccountMember:getAccountMember", {
        "accountId": args.accountId,
        "email": args.email,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccountMember.
 */
export interface GetAccountMemberArgs {
    /**
     * Account ID (UUID) where the member resides
     */
    accountId?: string;
    /**
     * Member email
     */
    email: string;
}

/**
 * A collection of values returned by getAccountMember.
 */
export interface GetAccountMemberResult {
    /**
     * Account ID (UUID) where the member resides
     */
    readonly accountId?: string;
    /**
     * Acount Role ID (UUID)
     */
    readonly accountRoleId: string;
    /**
     * Name of Account Role assigned to member
     */
    readonly accountRoleName: string;
    /**
     * Actor ID (UUID)
     */
    readonly actorId: string;
    /**
     * Member email
     */
    readonly email: string;
    /**
     * Member's first name
     */
    readonly firstName: string;
    /**
     * Member handle, or a human-readable identifier
     */
    readonly handle: string;
    /**
     * Account Member ID (UUID)
     */
    readonly id: string;
    /**
     * Member's last name
     */
    readonly lastName: string;
    /**
     * User ID (UUID)
     */
    readonly userId: string;
}
/**
 * Get information about an existing Account Member (user)	by their email.
 * <br>
 * Use this data source to obtain user or actor IDs to manage Workspace Access.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prefect from "@pulumi/prefect";
 *
 * const marvin = prefect.getAccountMember({
 *     email: "marvin@prefect.io",
 * });
 * ```
 */
export function getAccountMemberOutput(args: GetAccountMemberOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAccountMemberResult> {
    return pulumi.output(args).apply((a: any) => getAccountMember(a, opts))
}

/**
 * A collection of arguments for invoking getAccountMember.
 */
export interface GetAccountMemberOutputArgs {
    /**
     * Account ID (UUID) where the member resides
     */
    accountId?: pulumi.Input<string>;
    /**
     * Member email
     */
    email: pulumi.Input<string>;
}
