// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The resource `serviceAccount` represents a Prefect Cloud Service Account. A Service Account allows you to create an API Key that is not associated with a user account.
 *
 * Service Accounts are used to configure API access for workers or programs. Use this resource to provision and rotate Keys as well as assign Account and Workspace Access through Roles.
 *
 * API Keys for `serviceAccount` resources can be rotated by modifying the `apiKeyExpiration` attribute.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as prefect from "@pulumi/prefect";
 * import * as time from "@pulumiverse/time";
 *
 * // NON-EXPIRING API KEY
 * const exampleServiceAccount = new prefect.ServiceAccount("exampleServiceAccount", {});
 * const ninetyDays = new time.Rotating("ninetyDays", {rotationDays: 90});
 * // Pass the time_rotating resource to the `api_key_expiration` attribute
 * // in order to automate the rotation of the Service Account key
 * const exampleIndex_serviceAccountServiceAccount = new prefect.ServiceAccount("exampleIndex/serviceAccountServiceAccount", {apiKeyExpiration: ninetyDays.rotationRfc3339});
 * ```
 *
 * ## Import
 *
 * Prefect Service Accounts can be imported via name in the form `name/my-bot-name`
 *
 * ```sh
 * $ pulumi import prefect:index/serviceAccount:ServiceAccount example name/my-bot-name
 * ```
 *
 * Prefect Service Accounts can also be imported via UUID
 *
 * ```sh
 * $ pulumi import prefect:index/serviceAccount:ServiceAccount example 00000000-0000-0000-0000-000000000000
 * ```
 */
export class ServiceAccount extends pulumi.CustomResource {
    /**
     * Get an existing ServiceAccount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceAccountState, opts?: pulumi.CustomResourceOptions): ServiceAccount {
        return new ServiceAccount(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'prefect:index/serviceAccount:ServiceAccount';

    /**
     * Returns true if the given object is an instance of ServiceAccount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceAccount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceAccount.__pulumiType;
    }

    /**
     * Account ID (UUID), defaults to the account set in the provider
     */
    public readonly accountId!: pulumi.Output<string>;
    /**
     * Account Role name of the service account
     */
    public readonly accountRoleName!: pulumi.Output<string>;
    /**
     * API Key associated with the service account
     */
    public /*out*/ readonly apiKey!: pulumi.Output<string>;
    /**
     * Timestamp of the API Key creation (RFC3339)
     */
    public /*out*/ readonly apiKeyCreated!: pulumi.Output<string>;
    /**
     * Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
     */
    public readonly apiKeyExpiration!: pulumi.Output<string | undefined>;
    /**
     * API Key ID associated with the service account
     */
    public /*out*/ readonly apiKeyId!: pulumi.Output<string>;
    /**
     * API Key Name associated with the service account
     */
    public /*out*/ readonly apiKeyName!: pulumi.Output<string>;
    /**
     * Timestamp of when the resource was created (RFC3339)
     */
    public /*out*/ readonly created!: pulumi.Output<string>;
    /**
     * Name of the service account
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Timestamp of when the resource was updated (RFC3339)
     */
    public /*out*/ readonly updated!: pulumi.Output<string>;

    /**
     * Create a ServiceAccount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ServiceAccountArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceAccountArgs | ServiceAccountState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceAccountState | undefined;
            resourceInputs["accountId"] = state ? state.accountId : undefined;
            resourceInputs["accountRoleName"] = state ? state.accountRoleName : undefined;
            resourceInputs["apiKey"] = state ? state.apiKey : undefined;
            resourceInputs["apiKeyCreated"] = state ? state.apiKeyCreated : undefined;
            resourceInputs["apiKeyExpiration"] = state ? state.apiKeyExpiration : undefined;
            resourceInputs["apiKeyId"] = state ? state.apiKeyId : undefined;
            resourceInputs["apiKeyName"] = state ? state.apiKeyName : undefined;
            resourceInputs["created"] = state ? state.created : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["updated"] = state ? state.updated : undefined;
        } else {
            const args = argsOrState as ServiceAccountArgs | undefined;
            resourceInputs["accountId"] = args ? args.accountId : undefined;
            resourceInputs["accountRoleName"] = args ? args.accountRoleName : undefined;
            resourceInputs["apiKeyExpiration"] = args ? args.apiKeyExpiration : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["apiKeyCreated"] = undefined /*out*/;
            resourceInputs["apiKeyId"] = undefined /*out*/;
            resourceInputs["apiKeyName"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["updated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ServiceAccount.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceAccount resources.
 */
export interface ServiceAccountState {
    /**
     * Account ID (UUID), defaults to the account set in the provider
     */
    accountId?: pulumi.Input<string>;
    /**
     * Account Role name of the service account
     */
    accountRoleName?: pulumi.Input<string>;
    /**
     * API Key associated with the service account
     */
    apiKey?: pulumi.Input<string>;
    /**
     * Timestamp of the API Key creation (RFC3339)
     */
    apiKeyCreated?: pulumi.Input<string>;
    /**
     * Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
     */
    apiKeyExpiration?: pulumi.Input<string>;
    /**
     * API Key ID associated with the service account
     */
    apiKeyId?: pulumi.Input<string>;
    /**
     * API Key Name associated with the service account
     */
    apiKeyName?: pulumi.Input<string>;
    /**
     * Timestamp of when the resource was created (RFC3339)
     */
    created?: pulumi.Input<string>;
    /**
     * Name of the service account
     */
    name?: pulumi.Input<string>;
    /**
     * Timestamp of when the resource was updated (RFC3339)
     */
    updated?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ServiceAccount resource.
 */
export interface ServiceAccountArgs {
    /**
     * Account ID (UUID), defaults to the account set in the provider
     */
    accountId?: pulumi.Input<string>;
    /**
     * Account Role name of the service account
     */
    accountRoleName?: pulumi.Input<string>;
    /**
     * Timestamp of the API Key expiration (RFC3339). If left as null, the API Key will not expire. Modify this attribute to force a key rotation.
     */
    apiKeyExpiration?: pulumi.Input<string>;
    /**
     * Name of the service account
     */
    name?: pulumi.Input<string>;
}
